### ISSUE TITLE
Build failing on azure MS hosted ubuntu vmImage (tried all versions) 

### ISSUE THREAD

**Issue by inibriandia** [mikemadison13/blt-azure-pipelines#8]
Error : `You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.`

Some plugins are not compatible with composer 2 yet as the stable version is relatively new.

I found a work around by downgrading composer (`sudo composer self-update --1`) before installing dependencies.

```
  - task: Bash@3
    displayName: 'Install Dependencies'
    inputs:
      targetType: 'inline'
      script: |
        sudo composer self-update --1
        composer install --no-interaction --prefer-dist
        npm install npm@latest -g
```
Is there a better/recommended way of building composer 1 plugins/modules with azure vmImages?

**Comment by mikemadison13** [comment]
Hi @inibriandia are you getting a specific error for this project with composer 2?

You should be able to remove the following line from your build script and stop the build from updating to composer 2. My templated yml file doesn't include this, so it must have been added by the project.

```
sudo composer self-update --1
```

**Comment by inibriandia** [comment]
Thank you @mikemadison13 for your quick response.
I added `sudo composer self-update --1` so that the job doesn't fail.
Since Wednesday, all Microsoft's self hosted linux vmImages come with composer 2 instead of 1.
The question was if there is a recommended/better way of building composer 1 modules/plugins without this work around of downgrading composer on every build.

**Comment by mikemadison13** [comment]
Not that I'm aware of, no. The only other option is to aggressively work with those plugin maintainers to get fixes in place ASAP to support composer 2. In my experience it's a pretty minimal update in almost all cases. Otherwise, just make sure that you've run composer updates on your project's composer.json (and possibly first removed the .lock file and vendor folder to flush the caches out) to make sure you have the most current version of all the other packages.

**Comment by mikemadison13** [comment]
Here's some examples:

https://github.com/acquia/blt-phpcs/pull/4
https://github.com/grasmash/drupal-security-warning/pull/11
https://github.com/acquia/blt/pull/4260

**Comment by inibriandia** [comment]
This is better than what I was hoping for.
Thank you.

**Comment by mikemadison13** [comment]
most welcome. good luck!
